vim.api.nvim_buf_set_keymap(0, 'i', 'qp', 'println!("{}", );<left><left>', { noremap = true })
vim.api.nvim_buf_set_keymap(0, 'i', 'qqp', 'println!("{} - {}", );<left><left>', { noremap = true })
vim.api.nvim_buf_set_keymap(0, 'i', '<a-q>p', 'println!("");<left><left><left>', { noremap = true })
vim.api.nvim_buf_set_keymap(0, 'i', 'qfp', 'println!("}");<left><left><left><left>', { noremap = true })
vim.api.nvim_buf_set_keymap(0, 'i', 'q[', ' {}<Left><CR><Esc>O', { noremap = true })
-- vim.api.nvim_buf_set_keymap(0, "i", "qp", 'println!("{}");<left><left><left><left>', { noremap = true })
